#!/usr/bin/env ash

# Execute certbot
certbot certonly --agree-tos --non-interactive --work-dir /state/work --config-dir /state/config --logs-dir /logs $CERTBOT_ARGS
# mkdir -p /state/config/live/test.com
# echo "Hello" > /state/config/live/test.com/cert.pem

# Fix file permissions

echo "CERTS_GID=$CERTS_GID"
echo "PGID=$PGID"

echo "Updating certs group ownership to gid=${CERTS_GID:-$PGID}"

echo "===== Before ====="
ls -lR /state/config/live/*/*.pem

chgrp "${CERTS_GID:-$PGID}" -R /state/config/live/*/*.pem
chmod "0750" -R /state/config/live/*/*.pem
chmod "0750" -R /state/config/archive/*/*.pem

echo "===== After ====="
ls -lR /state/config/live/*/*.pem

# Copy files over to /certs while preserving the file permissions
cp -p /state/config/live/*/*.pem /certs

echo "===== After copy ====="
ls -lR /certs